name: Fintech Enterprise CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  lint-and-test:
    name: 🛡️ Code Quality & Syntax Verification
    runs-on: ubuntu-latest 
    
    steps:
      - name: Check out do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Validar Sintaxe do Código (Anti-Bug de Indentação)
        run: |
          pip install flake8
          flake8 app/src/main.py --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy-local-cluster:
    name: ☸️ Automated Deployment (k3d)
    needs: lint-and-test 
    runs-on: self-hosted
    
    steps:
      - name: Check out do código
        uses: actions/checkout@v3

      - name: Buildar e Atualizar no Cluster
        run: |
          cd app
          docker build -t fintech-app:${{ github.sha }} .
          k3d image import fintech-app:${{ github.sha }} -c fintech-cluster
          cd ../k8s
          kubectl apply -f postgres.yaml
          kubectl apply -f service.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f ingress.yaml
          kubectl set image deployment/fintech-api-deployment fintech-core=fintech-app:${{ github.sha }}
          kubectl rollout status deployment/fintech-api-deployment --timeout=60s
