name: Fintech GitOps Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'k8s/deployment.yaml'

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate

  gitops-sync:
    needs: terraform-check
    # Aqui a mágica: Tente usar ubuntu-latest se o self-hosted não estiver disponível
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da Imagem
        run: docker build -t fintech-app:${{ github.sha }} ./app

      - name: Patch & Push Manifest
        run: |
          [ -f k8s/deployment.yaml ] || { echo "Manifesto não encontrado!"; exit 1; }
          sed -i "s|image: fintech-app:.*|image: fintech-app:${{ github.sha }}|g" k8s/deployment.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add k8s/deployment.yaml
            git commit -m "🚀 GitOps: Atualizado para ${{ github.sha }}"
            # Comando de PUSH com autenticação forçada para garantir passagem
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          else
            echo "Nenhuma alteração necessária, pulando commit."
          fi
