name: Fintech CI/CD Pipeline

# 1. GATILHO: Dispara a esteira toda vez que houver um 'push' na branch principal
on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Roda numa máquina virtual limpa fornecida pelo GitHub

    steps:
    # Passo 1: Baixa o código do seu repositório para dentro da máquina do GitHub
    - name: Check out do código
      uses: actions/checkout@v3

    # Passo 2: Configura o ambiente Python para rodar testes automatizados
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-node: '3.11'

    # Passo 3: Instala as dependências e roda o Linter (Checa se a indentação tá certa!)
    - name: Validar Sintaxe do Código (Anti-Bug de Indentação)
      run: |
        pip install flake8
        # Se houver erro de indentação ou sintaxe, o build quebra aqui e não vai pra produção!
        flake8 app/src/main.py --count --select=E9,F63,F7,F82 --show-source --statistics

    # Passo 4: Simula o Build do Docker para garantir que o Dockerfile está perfeito
    - name: Testar Build da Imagem Docker
      run: |
        cd app
        docker build -t fintech-app:${{ github.sha }} .
